// ====================================
// COMMERCIAL APPROVAL TAB — GUIDE CONTENT
// componentIds here must match the data-guide-id attributes placed in
// CommercialApprovalSummary.jsx.
// ====================================

export const components = {

    "ca-quote-lines": {
        title: "Finalized Quote Lines & Decision History",
        explanation: "The same commercial line items shown earlier in the workflow, plus a history table of every decision recorded at this gate for this enquiry — who decided, what they decided, and when. This is the final commercial review before a quote is released to the customer."
    },

    "ca-request-approval": {
        title: "Request Approval",
        explanation: "A lightweight \"please take a look at this\" ping, open to anyone once the case has reached this stage. It notifies exactly the users who hold Commercial Approval approval standing for this enquiry's hub, not everyone, and does not itself approve or change anything."
    },

    "ca-decision": {
        title: "Accept and Generate Quote Release / Reject / Send Back",
        explanation: "The final decision for this workflow's approval chain. Accepting requires a note and, if the final value falls outside the quote's own budgetary range, an explicit confirmation — it generates a real quote release document and moves the enquiry to Quote Released. Reject and Send Back both return the case to Ops Review, with a required note either way. All three only become available once Quote & Commercial has already approved this quote, and only to users who hold Commercial Approval standing for this enquiry's hub."
    },

    "ca-release-actions": {
        title: "Download Quote Document / Send Quote Release Email",
        explanation: "Appear once a quote release document has actually been generated by Accepting above. The download gives you the real generated .docx; Send Quote Release Email opens a prefilled email (using the \"Quote Release\" template from Business Masters → Email Templates) so you can send the release to the customer directly from here."
    }

};

export const workflowSteps = [

    {
        componentId: "ca-quote-lines",
        stepText: "Start by reviewing the finalized quote lines and this gate's own decision history for this enquiry."
    },

    {
        componentId: "ca-request-approval",
        stepText: "Optional: ping a specific hub's Commercial Approval approvers directly if you want their eyes on this before deciding."
    },

    {
        componentId: "ca-decision",
        stepText: "Once you hold Commercial Approval standing for this hub, Accept to generate the quote release and move the case to Quote Released, or Reject / Send Back to return it to Ops Review. This decision notifies the relevant hub approvers directly and is logged in the Audit Trail."
    },

    {
        componentId: "ca-release-actions",
        stepText: "After Accepting, download the generated release document or send it straight to the customer by email from here."
    }

];
